SRC_DIR = src
BUILD_DIR = build
TOOLS_DIR = tools

OBJS = $(BUILD_DIR)/uart_utils.o $(BUILD_DIR)/peripherals_utils.o $(BUILD_DIR)/motor.o $(BUILD_DIR)/encoder.o $(BUILD_DIR)/robot.o

BINS = $(BUILD_DIR)/$(BIN_NAME).elf

BIN_NAME = main

include $(TOOLS_DIR)/avr_common.mk